---
title: "Jellyfish Sighting Forecasts"
format:
  html:
    code-fold: true
---

```{r setup, include=FALSE}
source("setup.R")
knitr::opts_chunk$set(echo = TRUE)

lionsmane_top = extract_top_model(version = "v2", sp = "lionsmane")
moon_top = extract_top_model(version = "v2", sp = "moon")
# whitecross_top = extract_top_model(version = "v2", sp = "whitecross")
# comb_top = extract_top_model(version = "v2", sp = "comb")
```

# Today's Lion's Mane Jellyfish Sighting Forecast
```{r lionsmane, echo=FALSE}
# lionsmane_img = extract_im(version = "v2", v = lionsmane_top[1], model = lionsmane_top[2])

lionsmane_img = extract_im(version = "v2", v = lionsmane_top[1], model = "rf")
```

# Lion's Mane Jellyfish Sighting Forecast Animation
```{r lm animation, echo=FALSE}
# lionsmane_gif = make_movie(version = "v2", v = lionsmane_top[1], model = lionsmane_top[2])
lionsmane_gif = make_movie(version = "v2", v = lionsmane_top[1], model = "rf")
lionsmane_gif
```

# 7 day horizontal display
```{r lionsmane test, echo=FALSE}

library(grid)
library(gridExtra)

img1 <- extract_im(version = "v2", v = lionsmane_top[1], date = Sys.Date(), model = "rf")
img2 <- extract_im(version = "v2", v = lionsmane_top[1], date = Sys.Date() + 1, model = "rf")
img3 <- extract_im(version = "v2", v = lionsmane_top[1], date = Sys.Date() + 2, model = "rf")
img4 <- extract_im(version = "v2", v = lionsmane_top[1], date = Sys.Date() + 3, model = "rf")
img5 <- extract_im(version = "v2", v = lionsmane_top[1], date = Sys.Date() + 4, model = "rf")
img6 <- extract_im(version = "v2", v = lionsmane_top[1], date = Sys.Date() + 5, model = "rf")
img7 <- extract_im(version = "v2", v = lionsmane_top[1], date = Sys.Date() + 6, model = "rf")

grid.arrange(
  rasterGrob(img1), rasterGrob(img2), rasterGrob(img3),
  rasterGrob(img4), rasterGrob(img5), rasterGrob(img6),
  rasterGrob(img7),
  nrow = 1
)

```

# 3 day display
```{r lionsmane test, echo=FALSE}
img1 <- extract_im(version = "v2", v = lionsmane_top[1], date = Sys.Date(), model = "rf")
img2 <- extract_im(version = "v2", v = lionsmane_top[1], date = Sys.Date() + 1, model = "rf")
img3 <- extract_im(version = "v2", v = lionsmane_top[1], date = Sys.Date() + 2, model = "rf")

grid.arrange(
  rasterGrob(img1), rasterGrob(img2), rasterGrob(img3),
  nrow = 1
)
```

# 7 day scroll
```{r scroll, echo=FALSE}
library(htmltools)

imgs <- list(
  extract_im(version="v2", v=lionsmane_top[1], date=Sys.Date(), model="rf"),
  extract_im(version="v2", v=lionsmane_top[1], date=Sys.Date()+1, model="rf"),
  extract_im(version="v2", v=lionsmane_top[1], date=Sys.Date()+2, model="rf"),
  extract_im(version="v2", v=lionsmane_top[1], date=Sys.Date()+3, model="rf"),
  extract_im(version="v2", v=lionsmane_top[1], date=Sys.Date()+4, model="rf"),
  extract_im(version="v2", v=lionsmane_top[1], date=Sys.Date()+5, model="rf"),
  extract_im(version="v2", v=lionsmane_top[1], date=Sys.Date()+6, model="rf")
)

# Build HTML with scrollbar
div(
  style = "height:600px; overflow-y: scroll; border:1px solid #ccc;",
  lapply(imgs, function(x) tags$img(src = x, style="width:100%; margin-bottom:10px;"))
)

```






# Today's Moon Jellyfish Forecast
```{r moon, echo=FALSE}
# moon_img = extract_im(version = "v2", v = moon_top[1], model = moon_top[2])

moon_img = extract_im(version = "v2", v = moon_top[1], model = "rf")

```

# Moon Jellyfish Sighting Forecast Animation
```{r moon animation, echo=FALSE}
# moon_gif = make_movie(version = "v2", v = moon_top[1], model = moon_top[2])
moon_gif = make_movie(version = "v2", v = moon_top[1], model = "rf")
moon_gif
```


<!-- # Today's White Cross Jellyfish Forecast -->
<!-- ```{r whitecross, echo=FALSE} -->
<!-- whitecross_img = extract_im(version = "v2", v = whitecross_top[1], model = whitecross_top[2]) -->
<!-- ``` -->

<!-- # White Cross Jellyfish Sighting Forecast Animation -->
<!-- ```{r wc animation, echo=FALSE} -->
<!-- whitecross_gif = make_movie(version = "v2", v = whitecross_top[1], model = whitecross_top[2]) -->
<!-- whitecross_gif -->
<!-- ``` -->

<!-- # Today's Comb Jellyfish Forecast -->
<!-- ```{r comb, echo=FALSE} -->
<!-- comb_img = extract_im(version = "v2", v = comb_top[1], model = comb_top[2]) -->
<!-- ``` -->

<!-- # Comb Jellyfish Sighting Forecast Animation -->
<!-- ```{r comb animation, echo=FALSE} -->
<!-- # comb_gif = make_movie(version = "v2", v = comb_top[1], model = comb_top[2]) -->
<!-- # comb_gif -->
<!-- ``` -->