---
title: "gom-jellies-dev"
---

```{r setup, echo = FALSE, include = FALSE}
source("setup.R")
coast = read_coast()
coast_bbox = st_bbox(coast)

all = read_obs() %>%
  filter(source == "record") %>%
  st_as_sf(coords = c("lon", "lat"), crs = 4326) %>% 
    mutate(year = year(date),
         month = factor(month(date, label = TRUE, abbr = TRUE),
                        levels = month.abb),
         type = as.factor(type))

obs = all %>%
  filter(type %in% c("lionsmane", "moon", "whitecross", "comb"))

```

For the [gom-jellies](https://github.com/BigelowLab/gom-jellies) project, observations come from community scientist reports. The following species have been selected for analysis:

  + *Cyanea capillata* (Lion's Mane)
  + *Aurelia aurita* (Moon)
  + *Staurostoma mertensii* (White Cross)
  + *Ctenophores* (Comb)

# All Observations
```{r, echo = FALSE}
ggplot() +
  geom_sf(data = coast, color = "black") +
  geom_sf(data = all, color = "steelblue", size = 1.5) +
  coord_sf(
    xlim = c(coast_bbox["xmin"], coast_bbox["xmax"]),
    ylim = c(coast_bbox["ymin"], coast_bbox["ymax"]),
    expand = FALSE
  ) +
  labs(title = "Distribution of All Observations") + 
  theme_minimal() +
  theme(axis.title = element_blank())
```

```{r, echo = FALSE}
ggplot(data = all, aes(x = factor(year))) +
  geom_bar(fill = "steelblue") +
  theme_minimal() +
  labs(
    title = "Number of Observations per Year",
    x = "Year",
    y = "Count"
  )

ggplot(all, aes(x = factor(month))) +
  geom_bar(fill = "steelblue") +
  theme_minimal() +
  labs(
    title = "Number of Observations per Month",
    x = "Month",
    y = "Count"
  )
```

# By Species
```{r, echo = FALSE}
ggplot() +
  geom_sf(data = coast, color = "black") +
  geom_sf(data = obs, aes(color = type), size = 1.5) +
  coord_sf(
    xlim = c(coast_bbox["xmin"], coast_bbox["xmax"]),
    ylim = c(coast_bbox["ymin"], coast_bbox["ymax"]),
    expand = FALSE
  ) +
  labs(title = "Filtered Distribution") + 
  theme_minimal() +
  theme(axis.title = element_blank())

ggplot(obs, aes(x = factor(year), fill = type)) +
  geom_bar() +
  theme_minimal() +
  labs(
    title = "Number of Observations per Year",
    x = "Year",
    y = "Count"
  )

ggplot(obs, aes(x = factor(month), fill = type)) +
  geom_bar() +
  theme_minimal() +
  labs(
    title = "Number of Observations per Month",
    x = "Month",
    y = "Count"
  )

```


